version: '3'

services:
  kong-dbless:
    depends_on:
      - calculator
      - weather
    image: kong:3.5.0
    container_name: kong-dbless
    volumes:
      - "./kong.yaml:/kong/declarative/kong.yaml"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
  calculator:
    image: svc-calculator:latest
    container_name: calculator
    ports:
      - "8081:8080"
  weather:
    image: svc-weather:latest
    container_name: weather
    ports:
      - "8082:8080"
